### ISSUE TITLE
"Enable Image Caching" permissions error

### ISSUE THREAD

**Issue by Fridgemagnet** [linuxserver/docker-overseerr#20]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
After enabling the new experimental image caching feature images should be saved to a cache location (/app/overseerr/.next/cache/images)

## Current Behavior
Due to a permissions error the image files cannot be saved to the cache location (/app/overseerr/.next/cache/images)

## Steps to Reproduce

1. Settings -> General -> enable "Enable Image Caching"
2. Multitude of error log entries stating a permissions error.

## Environment
**OS:** Linux Mint 19.3 Tricia
**CPU architecture:** x86_64
**How docker service was installed:**
Docker and docker-compose were installed using the official documentation found on docs.docker.com

## Command used to create docker container (run/create/compose/screenshot)
Portainer stack. Docker-compose format taken from official documentation: https://github.com/linuxserver/docker-overseerr

## Docker logs
Example log output
03/10/2022 11:16:23
Failed to write image to cache up7t3n3tyP0QB0pR4t5f0rl4FEi3U7VbfV-KQT1rm-M= [Error: EACCES: permission denied, mkdir '/app/overseerr/.next/cache/images'] {
03/10/2022 11:16:23
  errno: -13,
03/10/2022 11:16:23
  code: 'EACCES',
03/10/2022 11:16:23
  syscall: 'mkdir',
03/10/2022 11:16:23
  path: '/app/overseerr/.next/cache/images'
03/10/2022 11:16:23
}

**Comment by drizuid** [comment]
**note:** we do not support or recommend using portainer to deploy containers due to the many issues it can introduce.
That said, you need to provide your compose that you used in portainer for us to assist you.

I will add that I enabled this experimental feature without any errors at all.

**Comment by Fridgemagnet** [comment]
Recommendation noted.... but I will continue using Portainer.
I stated that I used the docker-compose from the official linuxserver overseerr page. Here it is anyway:
```
---
version: "2.1"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
```
